<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SoldierTotalColumn</RootNamespace>
    <AssemblyName>SoldierTotalColumn</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(CacheFolder)\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Log4Net">
      <HintPath>$(CacheFolder)\log4net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameFolder)\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(GameFolder)\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameFolder)\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameFolder)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameFolder)\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(GameFolder)\UnityEngine.UIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(GameFolder)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GameFolder)\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Sirenix.OdinInspector.Attributes">
      <HintPath>$(GameFolder)\Sirenix.OdinInspector.Attributes.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyOutputToDepot" AfterTargets="Build">
    <ItemGroup>
      <BuiltArtifacts Include="$(TargetPath)" />
      <BuiltArtifacts Include="$(TargetDir)$(TargetName).pdb" />
      <ModStaticFiles Include="$(MSBuildProjectDirectory)/mod/**/*" />
    </ItemGroup>

    <Copy
      SourceFiles="@(BuiltArtifacts)"
      DestinationFolder="$(ModInstanceFolder)/assembly/common"
      SkipUnchangedFiles="false"
    />

    <Copy
      SourceFiles="@(ModStaticFiles)"
      DestinationFiles="@(ModStaticFiles->'$(ModInstanceFolder)/%(RecursiveDir)%(Filename)%(Extension)')"
      SkipUnchangedFiles="true"
    />
  </Target>
</Project>
